// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC4Idtxcx75lkp1r3CgzhYv_mWnG1rLWI',
    appId: '1:164229204047:web:e753bacd80313a7a6e023a',
    messagingSenderId: '164229204047',
    projectId: 'my-digital-diary-b391c',
    authDomain: 'my-digital-diary-b391c.firebaseapp.com',
    storageBucket: 'my-digital-diary-b391c.firebasestorage.app',
    measurementId: 'G-R11V7Y0QK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuUokmMg0qzhmarHPT_7_1FQ0sG-R8e7k',
    appId: '1:164229204047:android:180f074407bcb4846e023a',
    messagingSenderId: '164229204047',
    projectId: 'my-digital-diary-b391c',
    storageBucket: 'my-digital-diary-b391c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBctZt3jthJj4WYgmA4nlY7R30j5dctbvE',
    appId: '1:164229204047:ios:7820dee76817cb1e6e023a',
    messagingSenderId: '164229204047',
    projectId: 'my-digital-diary-b391c',
    storageBucket: 'my-digital-diary-b391c.firebasestorage.app',
    iosBundleId: 'com.example.personalMonitorMobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBctZt3jthJj4WYgmA4nlY7R30j5dctbvE',
    appId: '1:164229204047:ios:7820dee76817cb1e6e023a',
    messagingSenderId: '164229204047',
    projectId: 'my-digital-diary-b391c',
    storageBucket: 'my-digital-diary-b391c.firebasestorage.app',
    iosBundleId: 'com.example.personalMonitorMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC4Idtxcx75lkp1r3CgzhYv_mWnG1rLWI',
    appId: '1:164229204047:web:1eb53c8126db0baa6e023a',
    messagingSenderId: '164229204047',
    projectId: 'my-digital-diary-b391c',
    authDomain: 'my-digital-diary-b391c.firebaseapp.com',
    storageBucket: 'my-digital-diary-b391c.firebasestorage.app',
    measurementId: 'G-0FY0LJL661',
  );
}
